<?php

namespace MyApp\ShopBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    /*public function rechercheDQL ($critere){
        $query=$this->getEntityManager()->createQuery("SELECT e FROM MyAppShopBundle:Produit e WHERE e.libelle like : libelle" )
        ->setParametre('libelle', '%'.$critere.'%');
        return $query->getResult();
    }*/
}
