<?php

namespace MyApp\DoctorBundle\Repository;

/**
 * CabinetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class CabinetRepository extends EntityRepository
{

    public function findcabinet($id)
    {
        $q=$this->getEntityManager()->createQuery('SELECT v From MyAppDoctorBundle:Cabinet v  
                                          WHERE v.user_id =: id')->setParameter('id',$id);
        return $q->getResult();




    }
}
