my_app_doctor_homepage:
    path:     /
    defaults: { _controller: MyAppDoctorBundle:Default:index }

Add_Cabinet:
    path:     /addcabinet
    defaults: { _controller: MyAppDoctorBundle:Cabinet:add}

listCabinet:
    path:     /listCabinet
    defaults: { _controller: MyAppDoctorBundle:Cabinet:listCabinet}

rechercheCabinet:
    path:     /rechercheCabinet
    defaults: { _controller: MyAppDoctorBundle:Cabinet:rechercheCabinet}

map:
    path:     /map
    defaults: { _controller: MyAppDoctorBundle:Cabinet:map }

findCabinet:
    path:     /mycabinet
    defaults: { _controller: MyAppDoctorBundle:Cabinet:MyCabinet}

Cabinet:
    path:     /cabinet/{spec}
    defaults: { _controller: MyAppDoctorBundle:Cabinet:Cabinet}

reservation:
    path:     /reservation
    defaults: { _controller: MyAppDoctorBundle:Cabinet:reservation}


reservation1:
    path:     /reservation1
    defaults: { _controller: MyAppDoctorBundle:Cabinet:Reservation1}

updaterdv:
    path:     /updaterdv
    defaults: { _controller: MyAppDoctorBundle:Cabinet:updaterdv}